### ISSUE TITLE
if using Cuboid: false, plugin doesn't check for overlapping fields

### ISSUE THREAD

**Issue by johnfriedrich** [marcelo-mason/PreciousStones#1014]
Hi,
when trying to place a field with cuboid: false in Minecraft 1.8 with PS Build 6, the plugin doesn't check for overlapping fields.

Lets say player A protects a field and player B tries to place a field close to the field of player A, he is able to do so with cuboid set to false. (Player B can now grief/loot  player A's field)
If cuboid is set to true, the check works and players cannot place fields when they would overlap.

**Comment by marcelo-mason** [comment]
Will check on this tonight.

**Comment by marcelo-mason** [comment]
Tested this and cannot reproduce the issue.  It correctly rejects placing overlapping fields regardless of cuboid or not, tested using default fields.   Please paste here your field configs that you are using for the fields that are giving you the probs.  Maybe its other flags interfering.

**Comment by johnfriedrich** [comment]
Thanks, it wasn't possible for us to reproduce it either.

We enabled cuboid, did ps reload and tried to place an ore. During that process the protected field got lost for whatever reason, this is why we could place an ore at that time.

Anyway, thanks for your help.
