### ISSUE TITLE
/ps remove deleting wrong subfields

### ISSUE THREAD

**Issue by kunpapa** [marcelo-mason/PreciousStones#1015]
Players can delete main fields (town fields) from subfields.

Player in a sub-field execute /ps remove <user>, and this, instead of deleting allowed player from fields, it delete all fields on the position owned by <user>.

With this players can delete other fields conflicting with his position even if they are not the owners.

Tried it by updating to last version, but problem persist.

**Comment by marcelo-mason** [comment]
Will check on this tonight.
