### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1040]
I had noticed after 1.11.2 paperspigot that plugin makes my server crash becouse of no memory left. All 6gb are used on ram by your plugin. When removed your plugin everything is normal and dosn't use all 6 gb only 1gb max. With is really strage for me please try to fix it. By the way no errors are displaying

**Comment by marcelo-mason** [comment]
What version of paperspigot were you upgrading from?

**Comment by arturek1666** [comment]
To the newest :)

**Comment by arturek1666** [comment]
I am using database by the way.

**Comment by arturek1666** [comment]
I insert plugin to my testing server and it's fine but on my server it's not, I really don't know why it happens. I am 100% it's becouse of precios stone but why new created it's fine and one that a lot of players have it can't hold not really sure

**Comment by marcelo-mason** [comment]
> What version of paperspigot were you upgrading **_from_**?

**Comment by arturek1666** [comment]
I upgrade from 1.11 to 1.11.2 for one day it was fine and after that somehow all ram is full

**Comment by frizzbee30** [comment]
If your test server is a copy of your live environment, then doesn't that suggest that their is a subtle difference in config? We had this in the move from 1.11 to 1.11.2 (not with PS) and a lib folder which made migration a nightmare until spotted!! (and the server unusable)

If test isn't a clone of live, then it's effectively useless having it :)

PS has been fantastic for us through the whole spigot upgrade cycle.

**Comment by arturek1666** [comment]
Removed from mysql data and it works but I don't want to do that don't know what to do the config is good. There is error in data somewhere eh
