### ISSUE TITLE
Really danger bug making your server crash and will crash server every time becouse of ram loose.

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1043]
about 3 weeks ago i write to you about issue that my server was using full ram and server crash because of your plugin and finally I find out why. I find out that one of my player did that by accident. If you place an region close to other person region. and than do /ps expand it will crash a server. At least that's what one of my players tells me. I hope he tell me write about it. I hope you will check it out. And if that's true it will be fixed.

**Comment by marcelo-mason** [comment]
Thanks, will test this out.
