### ISSUE TITLE
Idea - idea - idea!

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#1044]
I was thinking if there were possibilities for some PS to show it's boundries, like in Kingdoms when claiming a piece of land, the markers for that area are able to turn on and off... 

Is it possible to link blocks, i now have over 2000 cityplots in my map, and the server is remembering them all, and it all has to do with coordinates, i know, but if this was linkable for straight roads, just place one on the beginning of a road, and it suggests to place the other stone on the otherside of the road, and it takes all this area in between with it... I know, area is expandable, but that does not work all the time fluently and is a bit difficult, when different plugins mirror the commands expand and con...- con... see what i mean?...

Last idea and then i leave it, is it possible to introduce a GUI for all active stones. If i stand in an area and do not know what it's flags and settings are, a simple /PS SET should open a GUI that tells at first that you are in area x, or area x,y and z . Then click on the area that is a colored block, and it gives the name of the area, by clicking one of them, it shows type, flags, size, etc and are adjustable....
Really, a GUI is so enormous handy..... Hope you like it.

**Comment by krustymk** [comment]
fence-on-place flag ;)
ps info does nearly all the GUI stuff you asked for
Perhaps hit his 'Donate' button and read the wiki?

**Comment by MrKiller01** [comment]
Sorry guys, as of March 2018 I took hold of a copy of your TheAmigo's server and made it part of my server. Even in that config file of your copy Krusty, I could not find the option you mentioned... Maybe Mr. Mason would like to elaborate?

**Comment by MrKiller01** [comment]
Never mind the gap in time.... I see you are far more important things doing.... must be.....
