### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by VikingOmu** [marcelo-mason/PreciousStones#1051]
`17.02 22:09:57 [Server] WARN [PreciousStones] Plugin PreciousStones v10.0.4 generated an exception while executing task 83
17.02 22:09:57 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
17.02 22:09:57 [Server] INFO at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363) ~[?:?]
17.02 22:09:57 [Server] INFO at ps.org.mcstats.Metrics.access$500(Metrics.java:68) ~[?:?]
17.02 22:09:57 [Server] INFO at ps.org.mcstats.Metrics$1.run(Metrics.java:255) ~[?:?]
17.02 22:09:57 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot11.jar:git-Spigot-b4417b8-3c48711]
17.02 22:09:57 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot11.jar:git-Spigot-b4417b8-3c48711]
17.02 22:09:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_05]
17.02 22:09:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_05]
17.02 22:09:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
17.02 22:09:57 [Server] WARN [ChestShop] Plugin ChestShop v3.8.12 generated an exception while executing task 93
17.02 22:09:57 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
17.02 22:09:57 [Server] INFO at com.Acrobot.ChestShop.Metrics.postPlugin(Metrics.java:335) ~[?:?]
17.02 22:09:57 [Server] INFO at com.Acrobot.ChestShop.Metrics.access$400(Metrics.java:57) ~[?:?]
17.02 22:09:57 [Server] INFO at com.Acrobot.ChestShop.Metrics$1.run(Metrics.java:223) ~[?:?]
17.02 22:09:57 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot11.jar:git-Spigot-b4417b8-3c48711]
17.02 22:09:57 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot11.jar:git-Spigot-b4417b8-3c48711]
17.02 22:09:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_05]
17.02 22:09:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_05]
17.02 22:09:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]`

I keep getting these error :(

**Comment by MDelgadoCCM** [comment]
PS v10.0.4 is a real old version, were at 10.5.x

**Comment by marcelo-mason** [comment]
Upgrade PS, you must have an old version with MCStats still installed in it.
