### ISSUE TITLE
Limit the blocks

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1057]
I could not find out how I can limit placed blocks for example group player can only place 5 diamond blocks and than it will inform that he max his limit of placed blocks or something like that. If this feature already exists please tell me how thank you

**Comment by marcelo-mason** [comment]
yep it exists

**Comment by marcelo-mason** [comment]
http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#limits
