### ISSUE TITLE
Teleportation to region

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1062]
I would love to see an option for player to teleport to there is an plugin but it's outdated so I would love to see this added into official prepossessions 
basicly /ps listtp
/ps tp (id)

**Comment by Omanoctoa** [comment]
I know this is relatively possible to do using the /ps locations (player_name) to get the locations of their fields, then use /tp (or /tppos) arturek1666 x,y,z-location of field. Of course the command would need to be used manually, and the coords found manually, and the destination set manually... Sounds like a lot of work lol

**Comment by arturek1666** [comment]
The problem is that i dont want go give permission  /tp x y z for players as then players will be able to teleport everywhere.

**Comment by Omanoctoa** [comment]
I didn't figure you would want to,and the alternatives just become more and more complicated.

One possible (and less-complicated) alternative is to set all of that field type to be teleport destinations. Then, have another simple, unobstructing field that players can name and use to teleport back to those other locations. Players could use it to return to their named fields at home. You could even make it a 'mine: true', but negate the damage, to make it a one-time teleport. I'm not certain how the teleport flags work as I haven't used them myself, but the mechanics are available.
