### ISSUE TITLE
BUG - flamming arrows can hurt in protect-animals/villagers and prevent-pvp area

### ISSUE THREAD

**Issue by andramil** [marcelo-mason/PreciousStones#1064]
Players can kills animals using flaming arrows event if protect animals flag is on. It happens only on my 1.11.2 server ( have 1,8 and 1.9 too but it works correctly on them)

I have the newest version of PS for 1.11
I have spigot 1.11.2

**Comment by andramil** [comment]
It event pass throught no-pvp flag

**Comment by Coldene** [comment]
**no-projectile-throw: true** 
Hmmm!
