### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by krustymk** [marcelo-mason/PreciousStones#1081]
a way to have the price of the field increase the more of that field type the player buys
for example
1st home protection the player buys 1 gold
2nd 2 gold
3rd 4 gold

Thanks for looking :)

**Comment by Coldene** [comment]
As far as I can tell you can already do this but would need to make 
individual claim types for each higher price claim and then set limits 
quite low for each claim forcing players to have to buy higher price 
each extra one.

So 3 claims all Claim I type but higher cost each extra 1 they want?

"Claim I" limits 1. Cost 15K
"Claim I Upgrade 1" limits 1. Cost 30K
"Claim I Upgrade 2" limits 1. Cost 45K
"Claim I Upgrade 3" limits 1. Cost 60K
Claim I Upgrade 5 has same stats as 
all the other Claim I just more cost 
and they can only use 1 of each forcing them
to have to pay higher each time.

Something like that?

You could also try hidden tags such as color tags that have nothing after
them to try give each block the same name but a different NBT name tag
so they all look the same but are different as far as PreciousStones can tell?
Example
 Title: "&2&l&r&fClaim I"
meta-name: "&2&l&r&fClaim I"
 Title: "&4&l&r&fClaim I"
meta-name: "&4&l&r&fClaim I"
 Title: "&6&l&r&fClaim I"
meta-name: "&6&l&r&fClaim I"
All have the same plain white name but different tags.
They wont stack or merge.
Might work for individual pricing id thing?

**Comment by krustymk** [comment]
Ill give that a go, thanks

**Comment by marcelo-mason** [comment]
I'll be adding this soon, maybe a flag.  Probably over the weekend ill do it.

**Comment by krustymk** [comment]
@marcelo-mason Pizza/Beer money on its way to you
Thanks for your continued support of this excellent plugin :)
