### ISSUE TITLE
Killing animals and players

### ISSUE THREAD

**Issue by andramil** [marcelo-mason/PreciousStones#1082]
On spigot 1.11 PS 1.11 people can kill other players and animals on fileds event with protect animals flag and no pvp flag using flaming bows.

If needed I can make short video as proof.

**Comment by Coldene** [comment]
Please try 
/ps insert no-projectile-throw
inside one of those fields, if it dont work you will need to 
adjust the field flag's list in config.yml and add the flag there.

I forgot the command to insert this flag into all fields of a 
type that are already placed but there is one 

no-projectile-throw: true
prevent-potion-splash: true

All pstones with those prevent arrows/splash potions inside 
or from outside to inside the field. Works 100% against non allowed.
