### ISSUE TITLE
Bug with farmer villagers

### ISSUE THREAD

**Issue by pxblx** [marcelo-mason/PreciousStones#1085]
A villager inside a field with this configuration (https://pastebin.com/VPW2cEuf) can break and place wheat crops but not potatoes or carrots.

Spigot: git-Spigot-596221b-2c5c611 (1.12)
PreciousStones: v10.5.3 (for 1.12, build 2 on Jenkins)

**Comment by Coldene** [comment]
Crops is id 59 and only that. 59:7 I think is the max growth crops.
Pstones has never had the option as far as I remember to protect 
or not protect carrots, potato, beetroot, pumpkin blocks / stems etc.

Only crops. "minecraft:wheat"
Tis no bug, just a limitation.
