### ISSUE TITLE
Cuboid mixing

### ISSUE THREAD

**Issue by krustymk** [marcelo-mason/PreciousStones#1087]
Please close, turned out to be my fault
I have opened a new ticket with a problem i did discover during the process of sorting this one out (command-on-enter:)

After you have combined 2 field types in drawing mode you cant re enter drawing mode to alter the dimensions
'The field has sub fields inside of it and thus cannot be redefined' error pops up when you try

**Comment by Coldene** [comment]
It's odd that a resizeable sub field cannot be size edited once it is combined with a parent field.
It just means we have to plan a bit first as editing after is a rip it up and start again thing.
You could always just place another pstone of the plot containing type to extend the current plots area 
instead of rip up and start again?

**Comment by krustymk** [comment]
You misunderstand, im not adding a sub plot i am combining 2 stones in a mixing group
For example, 
Player puts a home field down with a volume of 1000, makes a nice square box
Then at some point in the future decides to buy a second stone with extra functionality for their home area (bouncer for example)
Being part of the same mixing group the second stone should add its flags to the primary stone (Look at Cuboid groups/Cuboid Mixing on the wiki). You get message to say it has done this. (though brief testing early indicates there may have a problem here also as the command to fly wouldnt fire, probably something simple though)
BUT.. if you now decide you want your protection to be a different shape and you try to enter drawing mode, you get the above error
Thats 2 stones making a single plot, not 1 main and a sub plot
Both have the same volume, ive tried the second with no volume defined but still the same

**Comment by krustymk** [comment]
Just want to add that i just tried it with another stone and it worked fine...
Obviously me being an idiot
again

**Comment by krustymk** [comment]
Definitely an issue here, spent a few hours trying different things 

Adding a second stone doesnt import the flags correctly (or at least not the 'command' flag)

If i combine a second stone with the following flags

  command-on-enter:
  - fly {player} 1
  command-on-exit:
  - fly {player} 0

I get the message the flags have been imported, but no flying..
However, if i place the stone on its own i can fly

**Comment by marcelo-mason** [comment]
fixed

**Comment by krustymk** [comment]
Top man!!! thanks :)

**Comment by marcelo-mason** [comment]
Let me know if you still have the prob with the subfields thing.  The thing fixed was actually the flags issue, but the subfields might still be happening so let me know.
