### ISSUE TITLE
Flags disabled by default "?prevent-mob" reverting to disabled on restart

### ISSUE THREAD

**Issue by PIE-yt** [marcelo-mason/PreciousStones#1094]
Maybe related to #1091 

Flags set disabled with the "?" prefix in the config.yml are reverting to disabled after being "/ps toggled" to enable them on server restart. 

The entries in the database for the "flags" key appear to be correct and are unaffected by a restart: ``{"disabledFlags":["prevent-teleport","prevent-animal-spawn","prevent-entry","protect-inventories","farewell-message"]}``

However the field behaves as though flags not listed in the database are disabled once the server restarts.
![2017-08-08_19 10 43](https://user-images.githubusercontent.com/18430220/29087595-58a51e10-7c6e-11e7-8d92-ba45bc699e4b.png) is the "/ps info" for the database entry above, notice that "prevent-mob-spawn" and "remove-mob" behave as disabled though not present in the database.

Using "/ps toggle" again to change a single flag on a field after a restart causes all disabled by default flags to be readded to the database.

Flags not disabled by default such as "farewell-message" have their state applied properly on server restart.

Hope this explanation makes sense.

Thanks very much for your time.

**Comment by marcelo-mason** [comment]
What version of PS you using?

**Comment by PIE-yt** [comment]
10.7.0 on the latest Spigot 1.12.1

**Comment by PIE-yt** [comment]
Appears to be fixed in 10.7.2 - many thanks for your time!
