### ISSUE TITLE
How i can disable drawing mode?

### ISSUE THREAD

**Issue by BaxAndrei** [marcelo-mason/PreciousStones#1128]
How I can disable [sneak-left-click] with a tool opening Cuboid / Drawing Mode

```
You are in drawing mode. Click on the block to finish.
Available protection: 505980 blocks
```

`cuboid: false `can help to disable?

**Comment by eUipKh** [comment]
Remove the flag.

**Comment by BaxAndrei** [comment]
I set `cuboid: false` and works.
