### ISSUE TITLE
TP stones do not work anymore

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#1169]
Having this issue for a few years, repeatedly let man know, nothing or no reaction to this.
I have in my server environment an old Amigo's server (yes, I kept it alive despite previous owner had to leave things) so, he had in his world many preciousStones, and two of them were Transport stones, White and Black stained glass.
Placing them is no problem, configuring them with /ps setname {name} works and with a wooden hoe I can rightclick it and it gives its data. The thing is, they do not work!

This here is the part that describes them
`- title: TP (White)
  block: white_stained_glass
  radius: 1
  custom-height: 4
  meta-name: '&bTransporter'
  meta-autoset: true
  meta-lore:
  - '&eTransporter, simply walk over when placed'
  - '&eIt covers an area of 1 radius'
  - '&eWith a max height of 4'
  - '&eEach additional Rank gains more'
  - '&e€100'
  limits:
  - 0
  - 4
  - 4
  - 10
  - 20
  - 250
  - 250
  ^teleport-on-entry: true
  ?welcome-message: true
  ?farewell-message: true
  cuboid: true
  price: 100
- title: TP Reciever (Black)
  block: black_stained_glass
  radius: 1
  custom-height: 4
  meta-name: '&bTP Reciever'
  meta-autoset: true
  meta-lore:
  - '&eThis is the destination for your TP stone'
  - '&eIt covers an area of 1 radius'
  - '&eMUST have the same name as the TP'
  - '&ePoint at both then /ps setname xxx'
  - '&eEach additional Rank gains more'
  - '&e€100'
  limits:
  - 0
  - 4
  - 4
  - 10
  - 20
  - 250
  - 250
  ^teleport-destination: true
  ?welcome-message: true
  ?farewell-message: true
  cuboid: true
  price: 100`
I shall add the config file here for anyone interested to look at it.
I was hoping that when there was a newer version, it would work again, but until now I still am sad....
[config.yml.txt](https://github.com/marcelo-mason/PreciousStones/files/6331772/config.yml.txt)

**Comment by xtomyserrax** [comment]
Hey, how are you? What version of spigot and PreciousStones are you using?

For the next time, please remember this is the actual updated repository of the plugin: https://github.com/elBukkit/PreciousStones

**Comment by MrKiller01** [comment]
Thanks for asking, still Corona-free and no complaints. (besides the usual from getting older (-:  lol)


[09:25:05] [Render thread/INFO]: [CHAT] This server is running CraftBukkit version 3046-Spigot-a25e8ed-1e1a5b7 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[09:25:05] [Render thread/INFO]: [CHAT] Checking version, please wait...
[09:25:05] [Render thread/INFO]: [CHAT] You are running the latest version
[09:25:27] [Render thread/INFO]: [CHAT] PreciousStones version 1.16.1.1
[09:25:27] [Render thread/INFO]: [CHAT] Authors: Phaed, NathanWolf and xtomyserrax

Does this help you in any way?

and ....... How are you? (-:

**Comment by xtomyserrax** [comment]
Heeey, good, thanks for asking!

Latest version is 1.16.1.14 ; You should update here: https://github.com/elBukkit/PreciousStones/tree/master

After updating, please confirm me if you still have this issue. Latest time I used tp stones they worked perfectly for me! (did you set the names correctly when setting the field?) Your configuration seems fine though Im not a pro with this features as I havent coded them

Also, why are you running on CraftBukkit? Try using Paper or Spigot as it will improve performance and server compability with plugins.

**Comment by MrKiller01** [comment]
I feel foolish when I ask you to give me a straight link to the newest file, it seems that wandering around on github does not help me.... I have no idea how to manage there....
I run Spigot, version 1.16.5, but when asking the server for 'version', it gives that craftbukkit text, must have been the core beneath Spigot... 
 -  -  -  -  -  -  -  - -  -  - -  -  -  - - - - - - - - - ------------
I am no programmer these days, so, help me out please....

Is it possible for you guys to link your effort directly from Spigotmc.org pages when looking for Preciousstones there???

**Comment by xtomyserrax** [comment]
Haha no problem. To download it you need to click the snapshot-download button and pick the latest number.

Here it is: https://jenkins.elmakers.com/job/PreciousStones/68/net.sacredlabyrinth.Phaed$PreciousStones/

The author of this plugin got inactive years ago. So we are mantaining it but dont really like to make a spigot page as its not official nor have the time to fix everything.

**Comment by MrKiller01** [comment]
I understand. Thanks for your hard work, and that of your team members ofcourse.....

**Comment by MrKiller01** [comment]
So, I got another account made at Mojang, went into a test scene, and ..... that worked......
Silly of me, being highest level permitted never understood why it did not work for me, as my second in command, I leave her there just for testers, never occurred to me that I had too many rights and those stones did nothing to me. Should have seen that one coming.....  Thanks for helping me out, on our other server we had 1.16.13, but we never went into those kind of stones to begin with. As Amigos was a 'taken care of ...' project, there were things in it I wanted to keep working....
Come visit and see if you like the way it is now... www.druifjes.nl and go to the Amigos world, see if you find a big city where a lot stones are been used....

Again, thanks....

**Comment by MrKiller01** [comment]
hmmm, in Amigos world there are a lot of stones as I said, but they do not work.... pity, they made up a lot for running around....
Am gonna look into this ordeal, that Amigos has two worlds, World, where I tested it and TheAmigosWorld2, where all those blocks are in place that do not work... Gonna keep trying and testing, ..... let you know....

I did the same test there, and that worked too. Now I have to figure out why those stones placed by people who are not in the mood to visit, or any other reason not to visit, are not operating anymore, they should... but why.....

**Comment by MrKiller01** [comment]
I am now slowly replacing the stones (Transport/receiver) in the World of Amigos. It is not a big problem but it is the traveling that makes it harder. Luckily I have an old unchanged database on my server to see who what and especially where the stones are located. With a viewer I can locate them and restore the path.... So, gonna close this now. Thank you!
(WWW.SQLITEBROWSER.ORG)
