### ISSUE TITLE
SimpleClans War

### ISSUE THREAD

**Issue by gabizou** [marcelo-mason/PreciousStones#127]
So from my understanding the use of PreciousStones and SimpleClans is that when two clans are at war, the enemy clan is added to the PreciousStones allow lists (Jack oDeath don't deal damage, City Protection allows them to modify area, Snitch doesn't record them entering etc.)

I really wanted this functionality but even after just running a test server with:

CraftBukkit 1597
SimpleClans 1.9.1
PreciousStones 7.1.0
Vault 1.2.0
iConomy 5.01 (I prefer to have players be able to use /money top and ranking)

So. Here's what I do with those plugins:

I start the server running default perms. Fresh start.

1) Start server
2) Stop server
3) Configure SimpleClans for warring (set it to minimum of 1 player to rival for testing purposes)
4) Start server
5) Testers log in
6) Create Clan A and Clan B and Clan C (wanted to check whether if warring clans can indeed invade regions and bouncers, the other clan that isn't at war wouldn't)
7) Clans create a wall around themselves and place a City Protection (yes, I tested whether the protections were far enough from each other not to interact with each other)
8) Clan A and B rival, then /clan war start ClanATag
9) SimpleClans processes both clans at war and treats them as such.
Here's where it misses, either from SC or from the PS side
9) Clan A attempts to dig into Clan B's walls but Clan A can not dig into the walls due to permissions not granted from PreciousStones (this applies to all the protection blocks)

Now I checked whether PS was automatically adding the clans into the allowed list, and yes, PS was setting the clans' members' stones allowed to the clans as well as the member. So in that sense, PS is automatically finding the hook from SC to set the clans in the allowed list for the defending clan. 

Just was I understanding the documentation (which is somewhat scattered on BukkitDev and the wiki and the github wiki) that SC clans at war should be allowed into the protections of the PS from the warring clans or are they not supposed to change their protections at all?

**Comment by sandor111** [comment]
You guys got out off it but for me its still not working?? I just downloaded this plugin and i am using bove latest versions if some one joins my clan he is able to place/destroy block in my ps regions but when i declear war we can't destroy the enemy's base

**Comment by Meibisu** [comment]
1.11.2 Not Working
