### ISSUE TITLE
Integrate World Edit compatibility? Huge bypass currently.

### ISSUE THREAD

**Issue by Nananea** [marcelo-mason/PreciousStones#44]
Phaed, I've just now noticed that people can bypass all protections with the use of any of World Edit's commands (// super pickaxe, //replace, etc). 

Is there any way this can be changed, please?

My scenario is that people that donate to my server are allowed the use of some World Edit commands. Regardless of permissions set up with PStones, they are able to bypass those with super pickaxe or any commands with World Edit.

Thank you!

**Comment by xtomyserrax** [comment]
Heyy sorry for bumping this old one but how does the WorldEdit compability work? People can destroy protections with WE.

Should I enable something?

Thanks!
