### ISSUE TITLE
UUIDs not changing

### ISSUE THREAD

**Issue by cuddylier** [marcelo-mason/PreciousStones#817]
Hi

I'm using dev build 497, when players login who have changed their username, their fields do not update to their new username and remain unusable by their new username. How does the UUID conversion work in the newer versions? When will it convert to allowing the new name to edit in the regions?

**Comment by phaed420** [comment]
It does.  But there is one caveat.  They have to have logged at any time previously (while your server was running the new builds of PS with UUID functionality installed) with their old name to have their UUID saved.  Then when they log in with a different username PS can match the UUID and proceed to update all his fields.

If you have been running the old builds of PS that didn't have UUID functionality, and then upgraded, any user that signs in with their new username that hadn't previously signed in with their old username after the upgrade, will not have a UUID stored in the database, so they will not have their fields updated.  Players that change their name after they have already been playing on your upgraded server, should be detected fine.

Please let me know if this sounds like what happened to these players.  Or if its a bug with the detection.

To help with these old users, I have added a /ps migrate [old-username] [new-username] command to do the migration of fields from one name to another manually.

**Comment by cuddylier** [comment]
That sounds like exactly what happened, thank you for the detailed explanation. Is it safe to give /ps migrate to normal users? E.g. does it check the username history? If so, what is the permission since it's not listed here: http://preciousstones.shoutwiki.com/wiki/Main_Page#Permissions

**Comment by phaed420** [comment]
The perm is *preciousstones.admin.migrate*, you can find it inside the plugin.yml in the new builds.  Its a very powerful command as it could be used to steal someones entire protection set. I would advice only to give it to mods, who can verify that indeed this is the user before giving him control of someone elses fields.
