### ISSUE TITLE
Doors/chest protection + Protection blocks on the horizon?

### ISSUE THREAD

**Issue by shadowrokx** [marcelo-mason/PreciousStones#827]
I added the flags:
prevent-use: [64, 71, 54]
protect-inventories: true
to a the config of a protection block. Then I tested out in someones claims with no special permissions and no OP, and yet I was able to open chests, doors, furnaces, etc... and even able to steal things out of inventories.

Is this a bug or am I doing something wrong.
For reference this is the entire config of the protection block: 

- title: Protection

  block: emerald_block

  radius: 5

  custom-height: 11

  prevent-fire: true

  prevent-place: true

  prevent-destroy: true

  prevent-vehicle-destroy: true

  prevent-enderman-destroy: true

  prevent-explosions: true

  prevent-item-frame-take: true

  prevent-flow: true

  protect-crops: true

  protect-inventories: true

  prevent-use:

  - 64

  - 71

  - 54

  protect-animals: true

  protect-villagers: true

  meta-name: '&b&lProtection Block'

  meta-lore:

  - '&7Place_this_down_to_protect_an_11x11x11_area.'

  - '&7You_can_get_more_by_voting._(&b&l/vote&7)'

  prevent-place-blacklist:

  - 153

  ?welcome-message: true

  ?farewell-message: true

  ?prevent-portal-enter: false

  ?prevent-portal-destination: false

  ?prevent-portal-create: false

  ?prevent-vehicle-enter: false

  ?prevent-vehicle-exit: false

  ?prevent-teleport: false

  command-blacklisting: false

  can-change-owner: true

  enable-on-src: true

  mixing-group: 1

  hidable: true

  rentable: false

  buyable: false

  cuboid: true

  mask-on-disabled: 80

While I'm at it several players noticed that they could see protection in the sky on the horizon so I went to check and it's true! When you approach them they disappear, so I'm suspicious of them being client side... Is this because of precious stones? Is this a bug? A feature?

**Comment by dadus33** [comment]
Same issue here (regarding floating PS on the horizon)

**Comment by marcelo-mason** [comment]
Try removing the hidable flag off them.

**Comment by dadus33** [comment]
I tried removing it but still get flying protection blocks on the horizon.
