### ISSUE TITLE
Version 9.9.0 breaks 'CreativeControl'

### ISSUE THREAD

**Issue by frizzbee30** [marcelo-mason/PreciousStones#828]
Hi, I am still working on the combinations of this. However we noticed that the 9.9.0 update (possibly an earlier commit   ?#500 ) allows blocks that should be unbreakable under creative control (http://dev.bukkit.org/bukkit-plugins/creativecontrol/#c2389)  to be placed,broken with a respective 'drop'   while #496 causes no issues and thus disallows the drop.

 The blocks we use for PS stones are the high value blocks such as gold and emerald, and thus sought after. It  appears that the plugin overrides creative control. I know this is not an issue with preciousstones itself, but it does cause problems and restrict upgrades. A number of servers require GM 1 players to be contained/controlled in their actions, and also run creative worlds alongside survival etc, as well as  GM 1 in survival. Thanks

**Comment by marcelo-mason** [comment]
How is your setup?  You use creative control to prevent the removal of field blocks once they are placed?  If so maybe adding the "single-use" flag to those fields could fix your issue.

**Comment by frizzbee30** [comment]
Hi, thanks for getting back. We use creative control so that players with GM 1 can't place stones (as we use diamonds blocks, gold etc) then break them in GM 0 and sell. Similarly when placed as a non -ps stone (in crouch) those blocks can't be broken by other players or the person who placed it. I'll look at single use, does it stop the player re using the stone as a PS field generator? If so, they wouldn't go for that as there is lots of placing/removing and replacing. Possibly we may need to look at blocking PS stone placing in GM 1 as a fix  (time for a revolt from our GM 1 capable players!)

**Comment by frizzbee30** [comment]
Hi looking at it, i don't think it would resolve our issue as the players whio are 'genuine' and purchase a block would lose it if they wished to move the stone. They would need to re mine or re purchase a protection stone block. We are looking at an alternative creative limiting plugin which may not present the issue, I'm just curious as to why the build change presented an issue we are still using the 'old' build). it may of course be down to the coding of creative control. i was just wondering as I know PS has had effects on other plugins int he past :) Cheers

**Comment by marcelo-mason** [comment]
Pretty sure its due to the new meta flags functionality and PS now taking control of all drops so it can serve the blocks with the item meta included on them.  Gonna see what I can do.

**Comment by frizzbee30** [comment]
Thanks, that's really appreciated. :)

**Comment by frizzbee30** [comment]
Hi, just wondering if this is amended in any of the latest Jenkins builds? :)  Thanks

**Comment by frizzbee30** [comment]
No longer an issue
