### ISSUE TITLE
How to disable /ps cuboid

### ISSUE THREAD

**Issue by baxandrei** [marcelo-mason/PreciousStones#831]
I want to disable /ps cuboid open, how i can make that?

**Comment by baxandrei** [comment]
can't place protection, and if i give acces to the comand, he have acces to /ps cuboid open

**Comment by marcelo-mason** [comment]
You are using "preciousstones.benefit.open.forcefield"?

**Comment by baxandrei** [comment]
my nodes:

    - -preciousstones.benefit.setradius
    - -preciousstones.benefit.setlimit
    - -preciousstones.benefit.density
    - -preciousstones.benefit.onoff
    - -preciousstones.benefit.open.forcefield
    - preciousstones.benefit.*
    - preciousstones.whitelist.*
    - preciousstones.admin.info

i want to give acces to create protections but i dont want users with acces to /ps cuboid open or close

**Comment by marcelo-mason** [comment]
They can't place protections with that setup?

**Comment by BaxAndrei** [comment]
I curently use that
- -preciousstones.benefit.setradius
- -preciousstones.benefit.setlimit
- -preciousstones.benefit.density
- -preciousstones.benefit.onoff
- -preciousstones.benefit.create.forcefield
- preciousstones.benefit.*
- preciousstones.whitelist.*
- preciousstones.admin.info

Now user cant access ps cuboid open but cant place fields. How i can restrict acces to ps cuboid open and let him to place fields?

**Comment by marcelo-mason** [comment]
Use the previous setup you posted.

**Comment by baxandrei** [comment]
Now user cant acces ps cuboid open .but can place fields. How i can restrict acces to ps cuboid open and let him to place fields? **** i am from phone phone srry.

**Comment by baxandrei** [comment]
With prevoirus they can place fields and have acces to ps cuboid open. How i can restrict acces only for ps cuboid open? Wuth that command they can extend fields and i dont want that.

**Comment by marcelo-mason** [comment]
They can or they cant place fields?  I am thoroughly confused right now.

**Comment by marcelo-mason** [comment]
Here is the code

```
 else if (cmd.equals(ChatBlock.format("commandCuboid")) && plugin.getPermissionsManager().has(player, "preciousstones.benefit.create.forcefield") && hasplayer)
                    {
                        if (args.length >= 1)
                        {
                            if ((args[0]).equals(ChatBlock.format("commandCuboidOpen")) && plugin.getPermissionsManager().has(player, "preciousstones.benefit.open.forcefield"))
                            {
                                Field field = plugin.getForceFieldManager().getOneOwnedField(block, player, FieldFlag.CUBOID);

                                if (field != null)
                                {
                                    if (field.isRented())
                                    {
                                        ChatBlock.send(player, "fieldSignCannotChange");
                                        return true;
                                    }

                                    plugin.getCuboidManager().openCuboid(player, field);
                                }
                                else
                                {
                                    plugin.getCommunicationManager().showNotFound(player);
                                }
                            }
                            else if ((args[0]).equals(ChatBlock.format("commandCuboidClose")))
                            {
                                plugin.getCuboidManager().closeCuboid(player);
                            }

                            return true;
                        }
                    }
```

**Comment by BaxAndrei** [comment]
I am sorry for confustion. So. They can place fields and have acces to /ps cuboid open. How i can restrict acces only for /ps cubid open. I use last build form bukkitdev and soighot 1.8.3

**Comment by marcelo-mason** [comment]
I renamed it to *preciousstones.benefit.openclose.forcefield*

**Comment by marcelo-mason** [comment]
Download the latest dev build from Jenkins or else none of these changes are making are gonna work for you.  http://repo.sacredlabyrinth.net:8080/

**Comment by BaxAndrei** [comment]
Thanks. Now everything is going right.
And now I see that appears when you go out in the region and when you leave the region.
Thank you so much for helping me. 
I appreciate your work!
I use PreciousStones from the first versions.
Cheers!
