### ISSUE TITLE
Block type list

### ISSUE THREAD

**Issue by jamesona** [marcelo-mason/PreciousStones#832]
This is more of a question than a request; I looked for a while and wasn't able to see anyone with my same use case.

I want to set up automatic grief prevention, based on nothing more than user placed blocks. When a user places any regular building block, it would obviously create a field for them. If they place any other regular building block within the field created by the first, that new block would add to the cuboid block allowance, as normal, regardless of which trigger block was placed.

I tested this on my own to see if it was possible, but it didn't work. 
Is this something that would be possible with the current system?

**Comment by marcelo-mason** [comment]
That wouldn't be possible with the PS system.  It doesn't work in a way that would make something like you describe possible.
