### ISSUE TITLE
Field-stone (block) border unloaded chunks

### ISSUE THREAD

**Issue by Fortifier42** [marcelo-mason/PreciousStones#834]
After having placed and - replicated using City Protection block (Diamond Block) - and City Protection, PeaceKeeper and Creature Repeller together. After removal of Creature Repeller and Peace Keeper the sponge and cobweb were no longer visible at the border of unloaded chunks
![2015-05-26_17 14 09](https://cloud.githubusercontent.com/assets/598503/7807040/55bf9374-03cb-11e5-85c8-d4d5580db74e.png)

**Comment by marcelo-mason** [comment]
remove hidable flag from fields
