### ISSUE TITLE
Meta-Data Errors and More...

### ISSUE THREAD

**Issue by NinjaSplat** [marcelo-mason/PreciousStones#836]
I noticed that when I use the meta-name and meta-lore flags, those work just fine, but then players are still able to place the normal block type inside of fields they aren't allowed in. Also, the c:clan identifier isn't working well, and sometimes, when players place a field, a random t:team identifier automatically allows itself onto the field, and it allows everyone to the field. Can you fix those?

**Comment by marcelo-mason** [comment]
> I noticed that when I use the meta-name and meta-lore flags, those work just fine, but then players are still able to place the normal block type inside of fields they aren't allowed in.

Can you expand on this:  What is a normal block type? What type of player (allowed or non-allowed).  Not sure I understand the bug.

**Comment by NinjaSplat** [comment]
By normal block, I mean a block type without a special name or lore. For example, when I use a meta-name and meta-lore for example on a protection field (diamond block), yes, the meta lores and names work, but a player is able to place normal diamond blocks inside of another player's field. Non-allowed means they have not been allowed to the field, and allowed means they are.

**Comment by marcelo-mason** [comment]
So you mean they don't protect anything?

**Comment by NinjaSplat** [comment]
Let me re-explain this so we're both on the same page. The meta name and meta lore flags work just fine, and work when placed as fields, but any player can place the same kind of block that DOES  NOT have any special lore or name inside of a field that they don't own. When they place it, no, they do not create fields, but they can just place them as normal blocks.

**Comment by NinjaSplat** [comment]
The fields do protect things, yes.

**Comment by NinjaSplat** [comment]
If my previous comment didn't help, I'll give you an example:
In my config, I edited the city protection by adding a meta-name and a meta-lore. Those features work as they should, but here's the problem:
- Players are able to place diamond blocks that DON'T have a custom name or lore inside of a pre-existing field that they don't have permission to place in, and when placed, they aren't placed as fields, but as regular blocks.
Any blocks that do have the meta-name and meta-lore DO protect a player's stuff, but players are able to place the same block but without the lore inside the field. I hope this made more sense. :)
