### ISSUE TITLE
Been having to deal with this for a while, why does it do this?

### ISSUE THREAD

**Issue by Htgan** [marcelo-mason/PreciousStones#837]
![2015-05-29_11 17 52](https://cloud.githubusercontent.com/assets/2534256/7874577/cf1da3b6-05f4-11e5-94b7-b2432711a516.png)

**Comment by marcelo-mason** [comment]
What is that supposed to be?  Protected blocks?

**Comment by Htgan** [comment]
Yes protection blocks or other kind of field blocks, they just show up outside the client rendered chunks like that. they're always present.

**Comment by marcelo-mason** [comment]
Interesting, weird.  I'll look into it.

**Comment by marcelo-mason** [comment]
Remove hidable flag from the fields.
