### ISSUE TITLE
Normal block drop protection block

### ISSUE THREAD

**Issue by WasdCat** [marcelo-mason/PreciousStones#855]
When my players put a normal block and broke it, drop a protection block

**Comment by marcelo-mason** [comment]
If you are using the meta flags, disable meta-autoset flag on your fields (autoset makes it so they get protection blocks out of regular blocks).  Disabling it makes it so they can only be acquired via shop or with /ps give.

**Comment by WasdCat** [comment]
wow, it work, thanks :+1:  but I can't use the command /ps give , in chat I can read "Not a valid command or insufficient permissions", but I've got "*" permission, Can you help me again? thanks and sorry my english, I'm spanish.

**Comment by marcelo-mason** [comment]
That command is brand new, only available in the latest dev builds from my jenkins.

**Comment by Taybosquee** [comment]
On that note, thanks for adding that command and so fast at that.
