### ISSUE TITLE
Blocks are not automatically placed as Precious Stones

### ISSUE THREAD

**Issue by Natalbee** [marcelo-mason/PreciousStones#860]
I've been having an issue where placing blocks like Diamond or Lapis Lazuli don't create their appropriate fields - they're just a normal block with a normal item name. But when I break them they turn into a field-creating block, and I am able to re-place them to create the appropriate field.

I don't remember having this problem with earlier versions of PS. Is there a new option or permission node that I'm not seeing? I really want to use this plugin, but right now it requires everyone to have an Iron or Diamond Pickaxe just to "create" a field.

It happens with OPs and players with the all-permission node (*), as well.

Please let me know, thank you.

**Comment by Natalbee** [comment]
No console errors, by the way.

**Comment by marcelo-mason** [comment]
This is due to the new *meta* flags on the config.  Remove them and it will go back to the way it used to be.

**Comment by marcelo-mason** [comment]
Here is the info on them: http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#meta-name

**Comment by Natalbee** [comment]
That was quick! Okay I'll try that right now. Thanks, Marcelo!

**Comment by Natalbee** [comment]
Yup, that did it. I probably should have read a bit more. Thanks again!
