### ISSUE TITLE
I can't mine!

### ISSUE THREAD

**Issue by Hampuswe** [marcelo-mason/PreciousStones#866]
Hi, I use Bukkit and the latest build of Precious stones for my server. The only problem is that I can't mine. When I mine coal I got a sky cannon instead of a piece of coal etc.
I though that you needed Silktouch to get a ps item. But it doesent seem like that and I can't find anything in the configuration.

Help is really appreciated
-Hampus H

**Comment by stevewall85** [comment]
Nope you don't need silk touch. You just need ps. You need to go into the configuration file and edit what blocks you want to do what or you can just delete the coal one to mine Coal

**Comment by stevewall85** [comment]
If it's fr an update issue there ice noticed in another post might be a slight update bug you can also back down to the last version you use for the meantime

**Comment by Hampuswe** [comment]
I prefer going down an update then thank you :+1:

**Comment by marcelo-mason** [comment]
Disable the meta-autoset flag on your fields.
