### ISSUE TITLE
/ps admin cleanup remove [days]

### ISSUE THREAD

**Issue by deevee1982** [marcelo-mason/PreciousStones#882]
In older version of PS was config setting cleanup: player-inactivity-purge-days. I tryed to add this in 9.8.3 but it dosn't work. Same with /ps admin cleanup remove [days]

How can I remove old plots ? Example older than 45 days.

**Comment by marcelo-mason** [comment]
This was added to the dev versions. Download the latest one from my Jenkins.

**Comment by deevee1982** [comment]
Can I use #536 on 1.8 spigot ?

**Comment by marcelo-mason** [comment]
You can.

**Comment by deevee1982** [comment]
Ok, I tested it on local serwer. I downloaded PS 9.8.3 (I use this on my network). I made field, then I changed to 10.0.3. Note Block disappeared but the protected field still exist. On network I use sql to storage fields info. What is the best way, to upgrade to 10.0.3 without lost any data? Should I remove all files from PreciouStone directory, then update .jar and start server then close server, edit config with mysql settings? I have 5900 cuboids on world and I don't like to lose any because players eat me ;)

**Comment by marcelo-mason** [comment]
Nothing should need to be changed when updating to 10.  Maybe the note block got erased cause the world data didn't get saved?  Test again with /save-all.  PS doesn't erase world blocks for no reason.

**Comment by deevee1982** [comment]
It look that after upgrade plot's working fine. Still 5900 fileds and Note Block are visible. Problem is that cleanup (45days) dosn't work. After restart I have still 5900 fields. it's so that cleanup time start from today? /ps admin cleanup remove is Not a valid command.
