### ISSUE TITLE
BUG 1.8 - Non allowed players placing blocks inside a PS.

### ISSUE THREAD

**Issue by Nachodiazv** [marcelo-mason/PreciousStones#890]
Hi,
When a player renames any block with the anvil, then he can place it inside any other player PS.

**Comment by marcelo-mason** [comment]
Just rename a block to any name and they can place it in anyone's PS? Or do they name it some specific name?

**Comment by Nachodiazv** [comment]
Any name, like asdada

**Comment by marcelo-mason** [comment]
Gonna do some testing tomorrow and fix it.
