### ISSUE TITLE
Newcommers also mine prescious stones instead or ore

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#898]
I have since beginning PS on my server, I am now that far so that other people can join, but when players are member or guest or owner, doesn't matter, if they hit coal, they'll get not coal but a precious stone. That is not what i want. How am i doing things right? 
Please help me...

**Comment by marcelo-mason** [comment]
Two options:

1. Remove meta-autoset: true from the fields.  Then you will have to give out the fields with the correct meta flags via shop or /ps give.

2. Have your players use /ps off when mining to get the ores.

3. Remove all meta flags from the fields, and the blocks only turn into fields when placed (but will no longer be items with custom names)

**Comment by MrKiller01** [comment]
What is the best way, because if i take the whole config file and only use one or two blocks (city plot / protection) then i could easily turn the rest off. How can i achieve that?

Thanks for reacting so fast.

**Comment by marcelo-mason** [comment]
Depends on what you want, each one has its pros and cons.  You delete fields by deleting them from the force-field-blocks list in the config.

**Comment by MrKiller01** [comment]
I have done option 1 you gave me, and i'm going to test it... Hope it works... I had earlier a city block and cityplot at my spawn point, i build there a switch on commandblock for sending the player to coordinates of a transporter. The non owner was not able to use that push button, i removed city protection, diamond block, and still, it did not work. When that same user was fas from the spawnpoint, standing in front of my transporter, and pressed any button that was configured, it works... Back at the spawn, he stood there and from a distance i pressed that button and whooosh gone he was... Strange...
