### ISSUE TITLE
Crash / Failed to load on 1.7.10 Craftbukkit and KCauldron

### ISSUE THREAD

**Issue by xJonL** [marcelo-mason/PreciousStones#899]
Tested using PreciousStones v9.8.2 and v.9.9.0 for 1.7.10

Craftbukkit:
v9.8.2 https://gist.github.com/7c2c22dd08313d570996

KCauldron 1448.133:
v9.8.2: https://gist.github.com/xJonL/06964d17146053a2bc35
v9.9.0: https://gist.github.com/xJonL/320e8c4faeb9661b52d3

KCauldron 1517.168
v9.8.2: https://gist.github.com/2e9acf3f09bf0d202025
v9.9.0: https://gist.github.com/xJonL/bda06ab88b5afa902995

**Comment by marcelo-mason** [comment]
1.7.* is no longer supported.

**Comment by xJonL** [comment]
I'm getting the same output with v9.7.0
https://gist.github.com/170766539ccd44fda6ff

**Comment by marcelo-mason** [comment]
That's a yaml error, probably something to do with the language file or config file.  Try to use the default ones to see if it goes away.

**Comment by xJonL** [comment]
I simply deleted the language.yml inside of the plugin and it regenerated itself and it seems to work now. Thanks, Marcelo.

P.S.
You're avatar is cute. :cake: 
haha just messing, but thanks for all the help and for making an awesome plugin
