### ISSUE TITLE
place/destroy prevent don't work

### ISSUE THREAD

**Issue by nicuch** [marcelo-mason/PreciousStones#904]
on spigot 1.8.8 prevents don't work...
players can build and destroy on claims...
i have 10.0.5 update

**Comment by marcelo-mason** [comment]
What was the version you were using prior that was working?

**Comment by nicuch** [comment]
probably 10.0.4

**Comment by marcelo-mason** [comment]
Did you upgrade Spigot?  Or was 1.8.8 working fine on 10.0.4?
