### ISSUE TITLE
Precious stones idea

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#908]
I'm having trouble to cityplot area's, they place, they say what they are, but sometimes the just placed stone does not respond. Is it Worldedit, worldguard, or any other plugin resides on the server during gameplay. So i need to find all my cityplot stones and test through /ps visualize if these individual work. Future request: How about a command that gives lines of the visual area of a PS stone, and when leaving the area, the markings will go away. So i can see when walking through my world, is a stone here active or not. This way will makes things very easy to maintain....

**Comment by marcelo-mason** [comment]
I can do that.  Not much code to write.

**Comment by MrKiller01** [comment]
And you don't know how happy i am with that answer, i was thinking further on my request, if it is not a problem, think along with me. I walk through my world, not only large areas but also high buildings have Precious Stones, maybe when pressing a simple command wil enlighten all blocks around me in an wide angle, bigger than visualize, but with colourcoded and a name tag visible who placed the block. So when walking through town, instantly all placed stones and their area's are becoming visible. If you make this, try to use thin lines that prevents lag... Thank you so much......

**Comment by MrKiller01** [comment]
I think this was a step or X too far.
