### ISSUE TITLE
Undocumented flags

### ISSUE THREAD

**Issue by RoboMWM** [marcelo-mason/PreciousStones#909]
Hi, am curious about the following flags which are only briefly mentioned in the wiki and not at all mentioned in the flag reference:
- allowedOnlyInside (allow-only-inside)
- allowedOnlyOutside (allow-only-outside?)
- mixing-group

**Comment by marcelo-mason** [comment]
The first two are actually `allowed-only-inside` and `allowed-only-outside`, they are in the flag reference.  The second one `mixing-groups` I just added to the reference.
