### ISSUE TITLE
Lore should only be applied when breaking a field block

### ISSUE THREAD

**Issue by dumptruckman** [marcelo-mason/PreciousStones#918]
Currently it seems that if I'm in creative mode and place a regular diamond block I can then break it to obtain a City Protection block. I would think that you are tracking each block's location so why not only have block break drop a City Protection block if it's actually that field block and let the regular blocks remain regular blocks when broken.

**Comment by marcelo-mason** [comment]
Super late but you can disable that by removing `meta-autoset: true` from your fields.
