### ISSUE TITLE
Just a silly question i hope you will answer

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#938]
I use PS, and i made a lot of use of the cityplot PS. Now i was doing something in the region and areashop (/rg   /as ) as i put myself into the lowest rank on my server, i found out that the blocks i placed myself were breakable by me.. I have no one around for testing, so i presume this is only because I placed that block, am i right? Is there a way for me to test the PS without using another account?
Thanks

Ps. i tried to delete something in someone elses stone area, and i still as guest (lowest rank) in gamemode 0 (survival) was able to damage parts within the visualized area! Maybe a way to show all stones that are in a radius around you (preferably adjustable) and see actually like holographic display where, what stone from owner... and it's radius range. So it makes them easier to search for gaps in the protection area....just simple lines would do!

**Comment by marcelo-mason** [comment]
I believe you can do /ps setowner and put some random name on there.   Then it will be like someone else placed it.

**Comment by MrKiller01** [comment]
I edited my q....

**Comment by marcelo-mason** [comment]
This plugin is no longer on active development, it is in maintenance mode only.  But you are welcome to find someone to code the features and send a pull request, I will merge it in.

**Comment by MrKiller01** [comment]
I do not know who wold be capable maintaining this, but if you put on the bukkit downloadpage a message, i'm very sure someone will contact you... A pit you are not able to work on this beautifull plugin!

**Comment by marcelo-mason** [comment]
I am maintaining it.  Read the README.md.  What I am not doing is adding in any new features.

**Comment by MrKiller01** [comment]
If you want progress, my advise isn't that bad, is it? I think there are people who would like to grab this plugin with both hands and still keep your name on it... It's a thought you know, would be a shame if this became a mothball plugin...

**Comment by marcelo-mason** [comment]
I've had bad experiences handing over my plugins to other's in the past.  Did that with SimpleClans, dude ended up rewriting it from scratch and created a massively buggy version that was not production ready and with changes nobody wanted.  Also had someone, with SimpleClans as well, trying to add features without understanding anything with DBs so was inserting and deleting columns from tables at runtime creating massive instability in the plugin for servers with massive tables.  

I don't have the time to be hand-holding a dev to make sure they don't wreck the experience for all the servers who rely on the plugin.

**Comment by MrKiller01** [comment]
I understand your problem with others, i can't do Java at all, i understand simple basic but i'm too old to learn even simple PEX commands from memory (-:   I still tend to forget that... Yet i hope you will find time and energy to improve some things over time.  not now, over time... or is it in time...?
Thanks for being friendly in your comments... Cheers from The Netherlands
