### ISSUE TITLE
next error

### ISSUE THREAD

**Issue by mat41997** [marcelo-mason/PreciousStones#941]
http://pastebin.com/A0TT1YGj

**Comment by marcelo-mason** [comment]
Try upgrading to PS 10.1.0

**Comment by mat41997** [comment]
next mysql error
http://hastebin.com/xebehaqoho.avrasm

**Comment by mat41997** [comment]
and
http://hastebin.com/nanogevono.avrasm

**Comment by mat41997** [comment]
my config
http://hastebin.com/iyutupuyib.sm
