### ISSUE TITLE
1.9 not-allowed can place\break armor stands inside city protection

### ISSUE THREAD

**Issue by spetznack** [marcelo-mason/PreciousStones#945]
Server version: Spigot 1.9 (git-Spigot-1a196e1-09b4549) yyyy-mm-dd 2016-03-08
Preciousstones version: Build #568

Players who are not allowed in a city protection can place\break as well as take\place armor from armorstands inside the city protection. I put the relevant part of config.yml and permissions the player has here: 
https://gist.github.com/spetznack/b181ca33c8ffa2d1261c

**Comment by marcelo-mason** [comment]
Tested this and works fine.  You need `protect-armor-stands: true` in your field.

**Comment by spetznack** [comment]
I had not added the flag, thank you!
