### ISSUE TITLE
Strange crafting bug

### ISSUE THREAD

**Issue by dumptruckman** [marcelo-mason/PreciousStones#947]
So, I made this plugin called Lock&Key and it has a recipe to turn a redstone block with item meta into 9 redstone dust with similar meta. However, whenever someone tries to use this recipe I get [this error](http://hastebin.com/uselozixex.avrasm) (upside down log - sorry). When they complete the craft they end up with regular redstone dust. I don't seem to have any problems with this recipe without PS installed.

**Comment by marcelo-mason** [comment]
That was fixed for 10.1.1 issue #942.

**Comment by dumptruckman** [comment]
Alright, thanks.
