### ISSUE TITLE
#build 8 unusual place block twice to set a ps field issue

### ISSUE THREAD

**Issue by frizzbee30** [marcelo-mason/PreciousStones#957]
Following on from the **fantastic** addition of blocking ps field placing in creative mode, we are having an issue with placing ps fields with build 8 in survival mode

If the auto metadata setting is disabled, regardless of how many times a block is placed, no ps field generates. There are no errors in console and the same is true if in op mode.

 All /ps commands are available

If auto set meta is then enabled, a block is placed and no field set. Breaking the block, the meta is evident. Re 'placing' the block sets the field as expected.

The block can then be broken and placed with success as many times as needed. Placing any non-meta ps blocks still refuses to generate a field until broken and then placed again.

Unfortunately we struggle just getting players to place a ps stone, never mind place, break and place again  :)

Thanks

**Comment by marcelo-mason** [comment]
There you go, that should do it.
