### ISSUE TITLE
IS THERE FOR MINECRAFT VERSION 1.7.10?

### ISSUE THREAD

**Issue by Franco200700** [marcelo-mason/PreciousStones#975]
Hi, I've been looking for Craftbukkit made Precious versions 1.7.10 and no, I could find. Please I need your help to find it, or just send the link of where you are.
And I've tried in versions 1.7.9 of Craftbukkit and run the command / ps I get: "Command not reconigzed" and simply does not work the plugin.
I hope to answer quick please. Thank you.

**Comment by marcelo-mason** [comment]
Looked in here? http://dev.bukkit.org/bukkit-plugins/preciousstones/files/

**Comment by Franco200700** [comment]
It does not appear, only 1.7.9. Is not there for 1.7.10?

**Comment by marcelo-mason** [comment]
That one or the next one should work, otherwise you might be out of luck.  My build server got hacked recently and I lost all the build history.

**Comment by Franco200700** [comment]
Mmm ... well, I see if it works in a way that engi me.

**Comment by marcelo-mason** [comment]
I added a Legacy version of PS to Jenkins that will build with all the latest patches but will work for 1.7/1.8.   

Jenkins:  http://104.236.246.108:8080/
