### ISSUE TITLE
no shows showOwner message

### ISSUE THREAD

**Issue by mat41997** [marcelo-mason/PreciousStones#977]
my config language

showOwner: '{yellow}wlasciciel {1.owner}'
showProtected: '{aqua}Obiekt Chroniony'
showProtectedLocations: '{dark-gray}Lokalizacja {gray}{2.coords}'

screen
![1](https://cloud.githubusercontent.com/assets/5884000/15425647/eb6aacb8-1e89-11e6-8ea7-289a49aef663.png)

timings
https://timings.aikar.co/v2/?id=e8b62601b7c04dba8d60edb4a6aec513&section=plugins#PreciousStones

**Comment by marcelo-mason** [comment]
The owner shows to non-allowed players when right clicking on a field to show info.
