### ISSUE TITLE
build #28 PS field not generated unless meta autoset = true

### ISSUE THREAD

**Issue by frizzbee30** [marcelo-mason/PreciousStones#980]
Hi, unless the meta-autoset: is set to true, placing the blocks in survival mode fails to generate a field?

Thanks

**Comment by marcelo-mason** [comment]
You got 3 options:

- Enable meta-autoset and have players mine the blocks as meta'd pstones
- Disable meta-autoset and create the meta'd blocks via shops or other means and give them out to players.  The plus side being they will still be able to mine the regular block as normal.
- Remove the meta flags altogether to have them behave like default.

**Comment by frizzbee30** [comment]
Hi, I didn't realise the meta flags could be removed (I'm presuming just remove them from the config), that's great.

 Basically the issue is that if they have meta flags when placed and broken by players in GM 1 they bypass all creative control plugins and drop the block. While they can't pick it up in creative mode, switching to survival allows them to obtain a 'free' precious stone, plus any other players they wish to abuse it for.

**Comment by frizzbee30** [comment]
That seems to have done the trick :)  wish I'd realised that a while ago, would have saved a lot of testing.. Thanks for the quick feedback, and the continued updates to a great plugin!  :D
