### ISSUE TITLE
Forester doesn't support Acacia or Dark Oak (Feature request)

### ISSUE THREAD

**Issue by Taybosquee** [marcelo-mason/PreciousStones#981]
The "tree-types" flag doesn't support Acacia or Dark Oak trees. This is hardly a show stopping issue, but it'd be a nice addition/fix. :)

http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#tree-types

**Comment by Taybosquee** [comment]
I just noticed the post on the front page. That's very disappointing to hear as PS was one of the best plugins ever made imo. Is there any hope for new life some time in the future?

**Comment by marcelo-mason** [comment]
It's alive, I still any non-trivial issues issues that come up.

**Comment by Taybosquee** [comment]
No, thank you for all the work you've done on this. And I'm glad to hear it is alive. :) (Thanks for this tree update by the way.)
