### ISSUE TITLE
How can people mine coal witheout get Launchpad

### ISSUE THREAD

**Issue by Marascraft** [marcelo-mason/PreciousStones#986]
Hello,
Maybe I misconfiguered the plugin, but my players can't mine coal or redstone normally since I installed precious stone.
Is there a setting for this ?
Sorry, for my bad english, I'm french.
Cordially,

**Comment by marcelo-mason** [comment]
Remove the meta-* flags from coal field config.

**Comment by Marascraft** [comment]
Thanks.
And now how can they get them ? Like turn Iron ore in sky canon ?
It s possible or not ?

**Comment by marcelo-mason** [comment]
Silk touch or through shops

**Comment by Marascraft** [comment]
And how can I sell them ? I just checked and Grief revert block has the same ID of the gold block, which is I think is normal.

**Comment by marcelo-mason** [comment]
You can use economy plugin and use the [price](http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#price) flag.   This will charge people when they place them.  Or you can just use blocks that are not found in the world and sell them in shops.

**Comment by Marascraft** [comment]
Thanks.
